// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'astro_astrologer';
  static const String PROJECT_VERSION = '1.0.2+3';
  static const String ASTROLGER_APP_SOUND = 'assets/audio/astrolger_app_sound.mp3';
  static const String GENRAL_SOUND_BOTH = 'assets/audio/genral_sound_both.mp3';
  static const String APP_ICON = 'assets/images/app_icon.png';
  static const String APP_LOGO = 'assets/images/app_logo.png';
  static const String BACKGROUND = 'assets/images/background.jpg';
}
